compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer:
    device: none
    pin_memory: true
  offload_param_device: none
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'yes'
main_training_function: main
mixed_precision: bf16
num_processes: 64
num_machines: 8
rdzv_backend: hccl
same_network: true
use_cpu: false