compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer:
    device: cpu
    pin_memory: true
  offload_param_device: none
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'yes'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_processes: 4
num_machines: 1
rdzv_backend: hccl
same_network: true
use_cpu: false